create database ALBERGUE;
USE ALBERGUE;

CREATE TABLE ESPECIE (
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE ESTADO(
	ID INTEGER NOT NULL primary KEY,
    NOMBRE varchar(50)
);

CREATE TABLE SEXO(
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE  ANIMAL (
	ID integer NOT NULL auto_increment primary KEY,
    NOMBRE VARCHAR (50),
    ESPECIE_ID integer,
    FOREIGN KEY (ESPECIE_ID) REFERENCES ESPECIE(ID), 
    RAZA varchar(50),
    EDAD integer,
    SEXO_ID INTEGER,
    foreign key(SEXO_ID) references SEXO(ID),
    PESO decimal(5,2),
    TAMANO decimal(3,2),
    ESTADO_ID integer,
    FOREIGN KEY (ESTADO_ID) references ESTADO(ID),
    FECHA_INGRESO timestamp,
    IMAGEN varchar(255),
    DESCRIPCION VARCHAR(1000)
);

CREATE TABLE PERSONA (
	ID INTEGER NOT NULL auto_increment PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(50),
    DIRECCION varchar(255)
);

CREATE TABLE ROL (
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE PERSONA_ROL (
	PERSONA_ID INTEGER,
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(ID),
    ROL_ID INTEGER,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID),
    PRIMARY KEY (PERSONA_ID,ROL_ID)
);

CREATE TABLE ADOPCION (
	ID INTEGER NOT NULL auto_increment PRIMARY KEY,
    PERSONA_ID INTEGER,
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(ID),
    ANIMAL_ID INTEGER,
    FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID),
    FECHA_ADOPCION TIMESTAMP,
    DESCRIPCION VARCHAR(1000)
);

CREATE TABLE TIPO_APADRINAMIENTO(
	ID INTEGER NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(50)
);

CREATE TABLE APADRINAMIENTO(
	ID INTEGER NOT NULL auto_increment PRIMARY KEY,
    PERSONA_ID INTEGER,
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(ID),
    ANIMAL_ID INTEGER,
    FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID),
    FECHA_INICIO TIMESTAMP,
    TIPO_APADRINAMIENTO_ID INTEGER,
    FOREIGN KEY (TIPO_APADRINAMIENTO_ID) REFERENCES TIPO_APADRINAMIENTO(ID),
    MONTO_MENSUAL DECIMAL (10,2),
    OBSERVACIONES VARCHAR(1000)
);

CREATE TABLE VOLUNTARIADO(
	ID INTEGER NOT NULL auto_increment PRIMARY KEY,
    PERSONA_ID INTEGER,
    FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(ID),
    FECHA_INICIO timestamp,
    FRECUENCIA VARCHAR(50),
    ACTIVO BOOLEAN
);

CREATE TABLE TAREA(
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (100)
);

CREATE TABLE VOLUNTARIO_TAREA(
	VOLUNTARIADO_ID INTEGER,
    FOREIGN KEY (VOLUNTARIADO_ID) REFERENCES VOLUNTARIADO(ID),
    TAREA_ID INTEGER,
    FOREIGN KEY (TAREA_ID) REFERENCES TAREA(ID),
    PRIMARY KEY (VOLUNTARIADO_ID,TAREA_ID)
);
